server:
  port: 8080

spring:
  application:
    name: okr-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/okr_agent
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/okr-agent
          jwk-set-uri: http://localhost:8081/realms/okr-agent/protocol/openid-connect/certs

logging:
  level:
    com.aibles.okragent: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs